services:
  postgres:
    image: postgres
    restart: always
    networks:
      - rwp-net
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: DB_Admin!7890
      POSTGRES_DB: rwp
    ports:
      - "7890:5432"
  pgadmin:  
    image: dpage/pgadmin4
    restart: always
    networks:
      - rwp-net
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@rwp.com
      PGADMIN_DEFAULT_PASSWORD: RWP_Admin!5050
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5050:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
  rwp:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: rwp-container
    working_dir: /var/www/html/
    user: "1000:1000"
    volumes:
      - ./php_dir:/var/www/html
    networks: 
      - rwp-net
    depends_on:
      - postgres
    ports:
      - "8081:80"
    environment:
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USER=rwp.no.reply@gmail.com
      - MAIL_PASS=wawvysunvwurrsie 
      - MAIL_FROM=rwp.no.reply@gmail.com
      - MAIL_DEBUG=0
      - EXCHANGERATE_API_KEY=fb8b38696a4eef5aea9a6023

networks:
  rwp-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"


volumes:
  db_data: